config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get 'pages/contact', to: 'pages#contact', as: 'contact'
  get 'pages/about', to: 'pages#about', as: 'about'
  get 'pages/help', to: 'pages#help', as: 'help'
  get 'users/new', to: 'users#new', as: 'new'

end

app/models/user.rb
# == Schema Information
# Schema version: <timestamp>
#
# Table nom: users
#
#  id         :integer         not null, primary key
#  nom        :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime

class User < ActiveRecord::Base
  attr_accessor :nom, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About me"
  end
  
  def help
    @title = "Help section"
  end

  def new
    @title = "Congrats and Welcome!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @title = 'Inscription'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Adding a dynamic title
  def title
    base_title = "Welcome on this Website"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About us", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">News</a></li>
      <li><a href="#">Products</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= image_tag("logo.png", :alt => "Application exemple", :class => "round") %>
  <nav class="round">
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Help', help_path %></li>
      <li><%= link_to 'Connexion', '#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheet.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheet' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <section class="round description">
        <p>
          <strong>Quibus</strong> ita sceleste patratis Paulus cruore perfusus reversusque ad principis castra multos coo
          pertos paene catenis adduxit in squalorem deiectos atque maestitiam, quorum adventu intendebantur eculei unco
          sque parabat carnifex et tormenta. et ex is proscripti sunt plures actique in exilium alii, non nullos gladii
          consumpsere poenales. nec enim quisquam facile meminit sub Constantio, ubi susurro tenus haec movebantur,
          quemquam absolutum.
        </p>
        <p>
          <strong>Primi</strong> igitur omnium statuuntur Epigonus et Eusebius ob nominum gentilitatem oppressi.
          praediximus enim Montium sub ipso vivendi termino his vocabulis appellatos fabricarum culpasse tribunos ut
          adminicula futurae molitioni pollicitos.
        </p>
        <p>
          <strong>Tempore</strong> quo primis auspiciis in mundanum fulgorem surgeret victura dum erunt homines Roma,
          ut augeretur sublimibus incrementis, foedere pacis aeternae Virtus convenit atque Fortuna plerumque dissidentes,
          quarum si altera defuisset, ad perfectam non venerat summitatem.
        </p>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About me</h1>
<p> Who I am ? </p>

app/views/pages/contact.html.erb
<h1>Contact</h1>

<div>
  <form action="post" id="forms">
    <label for="">Your Firstname
      <input type="text" name="firstname">
    </label>
    <label for="">Your Lastname
      <input type="text" name="lasttname">
    </label>
    <label for="description">Add your reason here</label>
    <textarea name="description" id="description" cols="50" rows="5"></textarea>
    <label for="genre">
      <input type="radio" name="gender" value="male"> Male<br>
      <input type="radio" name="gender" value="female"> Female<br>
      <input type="radio" name="gender" value="other"> Other
    </label>
    <button id="btn" type="button" onclick="">Send</button>
  </form>
</div>

app/views/pages/help.html.erb
<h1>Help</h1>
<div id="descriptionHelp">
  <p> In this section you can ask for help, I will respond as fast I can </p>
</div>

app/views/pages/help.htmnl.erb
<h1>Help</h1>
<p> In this section you can ask for help, I will respond as fast I can </p>

app/views/pages/home.html.erb
<h1>You don't have an account ?</h1>

<button class="btn_sign_up"><%= link_to 'Sign up now', new_path, :class => "signup_button round" %></button>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>